### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by slavakyrlan** [fellowsheet/study#7]
### Обобщенное решение

- [ ] Подключение докера
- [ ] Подключение БД
- [ ] Проверка работоспособности 

### Выходной результат

Корректная работа используя контейнер

## Как это запустить
1. Делаешь pull
2. Промежуточный этап. Найди в settings.py логин и пароль для бд, а также в docker-compose.yml. Поменяй на свой логин и пароль. С моими  не заработает.
3. Включаешь Docker Desktop 
4. В терминале заходишь в папку, в которой лежит Dockerfile. В нашем случае src (команда `cd src`, для выхода из папки `cd ..`)
5. В терминале пишешь `docker-compose up`, запускаешь и ждёшь. При первом запуске не помню, но при последующих появляется следующее

![Image](https://github.com/fellowsheet/study/assets/110399115/02a35362-cd28-4c99-ae6c-429a24154c7c)

Все отлично! Переходи на [http://localhost:8000/api/docs/](http://localhost:8000/api/docs/) и посмотри сколько эндпойнтов у нас уже есть :-P

## Как это было установлено.
1. Вот замечательный [гайд как установить Docker Desktop на Windows](https://stepik.org/lesson/1048969/step/2?unit=1057920) 
2. Поменяем немного структуру проекта. перенесём requirements.txt в папку с manage.py.
3. В папку куда мы перенесли requirements.txt добавим Dockerfile со следующим наполнением
```
FROM python:3   #это образ, на котором всё держится

EXPOSE 8000   #это открытие нужного нам порта

WORKDIR /usr/study/src  #тут указывается рабочая папка. Если таких папок в контейнере нет, они создаются. Следующие команды будут исполняться именно с этой папки
COPY requirements.txt ./  #добавляем в контейнер наш файлик с библиотеками

RUN pip install --no-cache-dir -r requirements.txt  #запускаем установку всех библиотек в контейнере

COPY . .   #добавляем в контейнер всё содержимое папки /study/src нашего проекта.
```
4. В корневую папку /study добавим `docker-compose.yml`. Заполняем файл следующим
```
version: '3'

services:
  django:
    container_name: django
    build: ./src
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./src:/usr/study/src/
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    environment:
      - POSTGRES_DB=mywebsite
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "8000:8000"
    # Зависимость от другого сервиса
    depends_on:
      - pgdb

  pgdb:
    container_name: pgdb
    # Использование готового образа postgres
    image: postgres
    restart: always
    # Задание переменных окружения для контейнера с postgres
    environment:
      - POSTGRES_DB=mywebsite
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    # Связывание тома с директорией в контейнере для сохранения данных postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data/
```
Мы написали настройки для двух контейнеров и связали их.
5. Осталось немного дописать в `settings.py`
Во-первых, добавим новые разрешенные порты:
```
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', 'pgdb', '172.25.0.2', '172.18.0.2']
```
Три последние нужны для postgres.
Во-вторых, добавим новое приложение для работы с postgres
```
INSTALLED_APPS = [
    #Другие приложения
    'django.contrib.postgres',
]
```
В-третьих, поменяем настройки БД:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'mywebsite',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'pgdb',  # localhost pgdb
        'PORT': '5432',
    }
}
```
Готово! Можно запускать с помощью `docker-compose up`!

## Немного о важном
Так как при запуске БД снова оказалась пустой, нужно сделать пару вещей ^_^
 `docker-compose run django python manage.py migrate`
 `docker-compose run django python manage.py createsuperuser`
Если модели претерпели изменения, то
 `docker-compose run django python manage.py makemigrations`
Всё, теперь точно всё должно работать🦖
